// Quiz data for grades 1-5, Math and Vietnamese Language
// Based on Vietnamese primary school curriculum (SGK 2024-2025)

export interface QuizData {
  grade: number;
  subject: string;
  chapter: string;
  chapterName: string;
  title: string;
  description: string;
  duration: number;
  questions: {
    questionText: string;
    questionType: "multiple_choice" | "fill_blank";
    options: string[];
    correctAnswer: string;
    points: number;
  }[];
}

export const quizData: QuizData[] = [
  // ===== LỚP 1 - TOÁN =====
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-1",
    chapterName: "Các số đến 10",
    title: "Kiểm tra Các số đến 10",
    description: "Bài kiểm tra kiến thức về các số từ 1 đến 10",
    duration: 20,
    questions: [
      { questionText: "Số nào lớn hơn: 7 hay 3?", questionType: "multiple_choice", options: ["A. 7", "B. 3", "C. Bằng nhau", "D. Không xác định"], correctAnswer: "A", points: 1 },
      { questionText: "Điền số thích hợp vào chỗ chấm: 1, 2, 3, ..., 5", questionType: "fill_blank", options: [], correctAnswer: "4", points: 1 },
      { questionText: "Số nào nhỏ nhất trong các số: 6, 3, 8, 2?", questionType: "multiple_choice", options: ["A. 6", "B. 3", "C. 8", "D. 2"], correctAnswer: "D", points: 1 },
      { questionText: "Viết số từ nhỏ đến lớn: 5, 2, 8, 1", questionType: "fill_blank", options: [], correctAnswer: "1 2 5 8", points: 1 },
      { questionText: "Số 6 nằm giữa hai số nào?", questionType: "multiple_choice", options: ["A. 4 và 5", "B. 5 và 7", "C. 7 và 8", "D. 3 và 4"], correctAnswer: "B", points: 1 },
      { questionText: "Có bao nhiêu số từ 1 đến 5?", questionType: "multiple_choice", options: ["A. 4", "B. 5", "C. 6", "D. 3"], correctAnswer: "B", points: 1 },
      { questionText: "Số liền trước số 9 là số nào?", questionType: "fill_blank", options: [], correctAnswer: "8", points: 1 },
      { questionText: "Số liền sau số 5 là số nào?", questionType: "fill_blank", options: [], correctAnswer: "6", points: 1 },
      { questionText: "Số nào lớn nhất có 1 chữ số?", questionType: "multiple_choice", options: ["A. 8", "B. 9", "C. 10", "D. 7"], correctAnswer: "B", points: 1 },
      { questionText: "Khoanh vào số chẵn: 3, 4, 5, 7", questionType: "multiple_choice", options: ["A. 3", "B. 4", "C. 5", "D. 7"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-2",
    chapterName: "Phép cộng trong phạm vi 10",
    title: "Kiểm tra Phép cộng trong phạm vi 10",
    description: "Bài kiểm tra kỹ năng tính cộng trong phạm vi 10",
    duration: 25,
    questions: [
      { questionText: "3 + 4 = ?", questionType: "multiple_choice", options: ["A. 6", "B. 7", "C. 8", "D. 5"], correctAnswer: "B", points: 1 },
      { questionText: "5 + 5 = ?", questionType: "fill_blank", options: [], correctAnswer: "10", points: 1 },
      { questionText: "2 + 6 = ?", questionType: "multiple_choice", options: ["A. 7", "B. 9", "C. 8", "D. 6"], correctAnswer: "C", points: 1 },
      { questionText: "1 + 8 = ?", questionType: "fill_blank", options: [], correctAnswer: "9", points: 1 },
      { questionText: "4 + ... = 7. Số cần điền là?", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "0 + 6 = ?", questionType: "multiple_choice", options: ["A. 0", "B. 6", "C. 60", "D. 5"], correctAnswer: "B", points: 1 },
      { questionText: "Lan có 3 cái kẹo, mẹ cho thêm 4 cái kẹo. Hỏi Lan có tất cả mấy cái kẹo?", questionType: "multiple_choice", options: ["A. 6 cái", "B. 7 cái", "C. 8 cái", "D. 4 cái"], correctAnswer: "B", points: 1 },
      { questionText: "7 + 3 = ?", questionType: "fill_blank", options: [], correctAnswer: "10", points: 1 },
      { questionText: "Có 2 con mèo và 5 con chó. Hỏi có tất cả mấy con vật?", questionType: "fill_blank", options: [], correctAnswer: "7", points: 1 },
      { questionText: "... + 5 = 10. Số cần điền là?", questionType: "fill_blank", options: [], correctAnswer: "5", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-3",
    chapterName: "Phép trừ trong phạm vi 10",
    title: "Kiểm tra Phép trừ trong phạm vi 10",
    description: "Bài kiểm tra kỹ năng tính trừ trong phạm vi 10",
    duration: 25,
    questions: [
      { questionText: "7 - 3 = ?", questionType: "multiple_choice", options: ["A. 3", "B. 5", "C. 4", "D. 6"], correctAnswer: "C", points: 1 },
      { questionText: "10 - 4 = ?", questionType: "fill_blank", options: [], correctAnswer: "6", points: 1 },
      { questionText: "8 - 8 = ?", questionType: "multiple_choice", options: ["A. 8", "B. 1", "C. 0", "D. 16"], correctAnswer: "C", points: 1 },
      { questionText: "9 - 5 = ?", questionType: "fill_blank", options: [], correctAnswer: "4", points: 1 },
      { questionText: "6 - ... = 2. Số cần điền là?", questionType: "fill_blank", options: [], correctAnswer: "4", points: 1 },
      { questionText: "Hàng có 8 quả táo, ăn mất 3 quả. Còn lại mấy quả táo?", questionType: "multiple_choice", options: ["A. 4 quả", "B. 5 quả", "C. 6 quả", "D. 3 quả"], correctAnswer: "B", points: 1 },
      { questionText: "10 - 7 = ?", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "5 - 0 = ?", questionType: "multiple_choice", options: ["A. 0", "B. 5", "C. 50", "D. 4"], correctAnswer: "B", points: 1 },
      { questionText: "... - 3 = 4. Số cần điền là?", questionType: "fill_blank", options: [], correctAnswer: "7", points: 1 },
      { questionText: "10 - 10 = ?", questionType: "fill_blank", options: [], correctAnswer: "0", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-4",
    chapterName: "Các số đến 20. Phép cộng và phép trừ trong phạm vi 20",
    title: "Kiểm tra Các số đến 20. Phép cộng và phép trừ trong phạm vi 20",
    description: "Bài kiểm tra kiến thức về các số từ 10 đến 20",
    duration: 20,
    questions: [
      { questionText: "Số mười lăm viết là:", questionType: "multiple_choice", options: ["A. 51", "B. 15", "C. 14", "D. 16"], correctAnswer: "B", points: 1 },
      { questionText: "Số 17 gồm mấy chục và mấy đơn vị?", questionType: "multiple_choice", options: ["A. 1 chục và 7 đơn vị", "B. 7 chục và 1 đơn vị", "C. 1 chục và 7 đơn vị", "D. 17 chục"], correctAnswer: "A", points: 1 },
      { questionText: "Số nào lớn hơn: 13 hay 16?", questionType: "fill_blank", options: [], correctAnswer: "16", points: 1 },
      { questionText: "Viết các số từ 11 đến 15:", questionType: "fill_blank", options: [], correctAnswer: "11 12 13 14 15", points: 1 },
      { questionText: "Số liền sau số 19 là:", questionType: "fill_blank", options: [], correctAnswer: "20", points: 1 },
      { questionText: "Số liền trước số 14 là:", questionType: "fill_blank", options: [], correctAnswer: "13", points: 1 },
      { questionText: "12 + 5 = ?", questionType: "multiple_choice", options: ["A. 15", "B. 17", "C. 18", "D. 16"], correctAnswer: "B", points: 1 },
      { questionText: "18 - 3 = ?", questionType: "fill_blank", options: [], correctAnswer: "15", points: 1 },
      { questionText: "Số nào nằm giữa 14 và 16?", questionType: "fill_blank", options: [], correctAnswer: "15", points: 1 },
      { questionText: "Số 20 gồm mấy chục?", questionType: "multiple_choice", options: ["A. 1 chục", "B. 2 chục", "C. 20 chục", "D. 0 chục"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-5",
    chapterName: "Điểm và đường thẳng. Đoạn thẳng",
    title: "Kiểm tra Điểm và đường thẳng. Đoạn thẳng",
    description: "Bài kiểm tra kiến thức về điểm, đường thẳng và đoạn thẳng",
    duration: 20,
    questions: [
      { questionText: "Điểm được kí hiệu bằng gì?", questionType: "multiple_choice", options: ["A. Một chữ cái in hoa", "B. Một số", "C. Một dấu chấm", "D. Một hình"], correctAnswer: "A", points: 1 },
      { questionText: "Đường thẳng có thể kéo dài bao xa?", questionType: "multiple_choice", options: ["A. Hết tờ giấy", "B. Không giới hạn", "C. 10 cm", "D. 1 mét"], correctAnswer: "B", points: 1 },
      { questionText: "Đoạn thẳng là phần của đường thẳng bị giới hạn bởi:", questionType: "fill_blank", options: [], correctAnswer: "hai điểm", points: 1 },
      { questionText: "Qua hai điểm có thể vẽ được bao nhiêu đường thẳng?", questionType: "multiple_choice", options: ["A. 1 đường thẳng", "B. 2 đường thẳng", "C. Nhiều đường thẳng", "D. Không vẽ được"], correctAnswer: "A", points: 1 },
      { questionText: "Đoạn thẳng AB có hai đầu mút là:", questionType: "fill_blank", options: [], correctAnswer: "điểm A và điểm B", points: 1 },
      { questionText: "Điểm M nằm trên đoạn thẳng AB khi nào?", questionType: "multiple_choice", options: ["A. M nằm gần A", "B. M nằm giữa A và B", "C. M nằm gần B", "D. M nằm ngoài AB"], correctAnswer: "B", points: 1 },
      { questionText: "Ba điểm thẳng hàng là ba điểm nằm trên:", questionType: "fill_blank", options: [], correctAnswer: "một đường thẳng", points: 1 },
      { questionText: "Đường thẳng khác đoạn thẳng ở điểm nào?", questionType: "multiple_choice", options: ["A. Đường thẳng dài hơn", "B. Đường thẳng không có giới hạn", "C. Đoạn thẳng dài hơn", "D. Giống nhau"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-6",
    chapterName: "Hình chữ nhật, hình vuông, hình tròn, hình tam giác",
    title: "Kiểm tra Hình học cơ bản",
    description: "Bài kiểm tra nhận biết các hình cơ bản",
    duration: 20,
    questions: [
      { questionText: "Hình vuông có mấy cạnh?", questionType: "multiple_choice", options: ["A. 3 cạnh", "B. 4 cạnh", "C. 5 cạnh", "D. 6 cạnh"], correctAnswer: "B", points: 1 },
      { questionText: "Hình tam giác có mấy đỉnh?", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "Hình nào có 4 cạnh bằng nhau?", questionType: "multiple_choice", options: ["A. Hình chữ nhật", "B. Hình tam giác", "C. Hình vuông", "D. Hình tròn"], correctAnswer: "C", points: 1 },
      { questionText: "Hình tròn có cạnh không?", questionType: "multiple_choice", options: ["A. Có 1 cạnh", "B. Có nhiều cạnh", "C. Không có cạnh", "D. Có 2 cạnh"], correctAnswer: "C", points: 1 },
      { questionText: "Hình chữ nhật có mấy góc vuông?", questionType: "fill_blank", options: [], correctAnswer: "4", points: 1 },
      { questionText: "Hình nào có 3 cạnh?", questionType: "multiple_choice", options: ["A. Hình vuông", "B. Hình tròn", "C. Hình chữ nhật", "D. Hình tam giác"], correctAnswer: "D", points: 1 },
      { questionText: "Quả bóng có hình gì?", questionType: "fill_blank", options: [], correctAnswer: "hình tròn", points: 1 },
      { questionText: "Cái bảng đen thường có hình gì?", questionType: "multiple_choice", options: ["A. Hình tam giác", "B. Hình tròn", "C. Hình chữ nhật", "D. Hình vuông"], correctAnswer: "C", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "toan",
    chapter: "chuong-7",
    chapterName: "Đại lượng và đo đại lượng",
    title: "Kiểm tra Đại lượng và đo đại lượng",
    description: "Bài kiểm tra kiến thức về độ dài, khối lượng và thời gian cơ bản",
    duration: 20,
    questions: [
      { questionText: "Đơn vị đo độ dài nào em đã học?", questionType: "multiple_choice", options: ["A. Lít", "B. Kilôgam", "C. Xăng-ti-mét", "D. Giờ"], correctAnswer: "C", points: 1 },
      { questionText: "Đơn vị đo khối lượng là:", questionType: "fill_blank", options: [], correctAnswer: "kilôgam", points: 1 },
      { questionText: "1 mét bằng bao nhiêu xăng-ti-mét?", questionType: "multiple_choice", options: ["A. 10 cm", "B. 100 cm", "C. 1000 cm", "D. 50 cm"], correctAnswer: "B", points: 1 },
      { questionText: "Để đo chiều dài bàn học, em dùng:", questionType: "multiple_choice", options: ["A. Cân", "B. Đồng hồ", "C. Thước kẻ", "D. Cốc"], correctAnswer: "C", points: 1 },
      { questionText: "Để đo khối lượng, em dùng:", questionType: "fill_blank", options: [], correctAnswer: "cân", points: 1 },
      { questionText: "Một ngày có bao nhiêu giờ?", questionType: "multiple_choice", options: ["A. 12 giờ", "B. 24 giờ", "C. 60 giờ", "D. 10 giờ"], correctAnswer: "B", points: 1 },
      { questionText: "1 giờ bằng bao nhiêu phút?", questionType: "fill_blank", options: [], correctAnswer: "60", points: 1 },
      { questionText: "Cậu bé cao 120:", questionType: "multiple_choice", options: ["A. Kilôgam", "B. Lít", "C. Xăng-ti-mét", "D. Phút"], correctAnswer: "C", points: 1 },
    ]
  },

  // ===== LỚP 1 - NGỮ VĂN =====
  {
    grade: 1,
    subject: "ngu-van",
    chapter: "chuong-1",
    chapterName: "Các âm và vần cơ bản",
    title: "Kiểm tra Các âm và vần cơ bản",
    description: "Bài kiểm tra nhận biết các âm, vần cơ bản và đánh vần",
    duration: 20,
    questions: [
      { questionText: "Chữ 'o' là nguyên âm hay phụ âm?", questionType: "multiple_choice", options: ["A. Phụ âm", "B. Nguyên âm", "C. Cả hai", "D. Không phải âm"], correctAnswer: "B", points: 1 },
      { questionText: "Chữ nào đứng sau chữ 'b' trong bảng chữ cái?", questionType: "multiple_choice", options: ["A. a", "B. c", "C. d", "D. e"], correctAnswer: "B", points: 1 },
      { questionText: "Chữ cái nào khác với các chữ còn lại: a, ă, â, b?", questionType: "multiple_choice", options: ["A. a", "B. ă", "C. â", "D. b"], correctAnswer: "D", points: 1 },
      { questionText: "Đọc tên chữ 'm' là:", questionType: "multiple_choice", options: ["A. Mờ", "B. Nờ", "C. Lờ", "D. Pờ"], correctAnswer: "A", points: 1 },
      { questionText: "Sắp xếp các chữ: a, c, b theo thứ tự bảng chữ cái:", questionType: "fill_blank", options: [], correctAnswer: "a b c", points: 1 },
      { questionText: "Có mấy nguyên âm đơn trong tiếng Việt?", questionType: "multiple_choice", options: ["A. 5", "B. 6", "C. 12", "D. 29"], correctAnswer: "A", points: 1 },
      { questionText: "Chữ nào đứng trước chữ 'g' trong bảng chữ cái?", questionType: "fill_blank", options: [], correctAnswer: "f", points: 1 },
      { questionText: "Các chữ a, ă, â giống nhau ở điểm nào?", questionType: "multiple_choice", options: ["A. Đều là phụ âm", "B. Đều là nguyên âm", "C. Đều là chữ viết hoa", "D. Không giống nhau"], correctAnswer: "B", points: 1 },
      { questionText: "Chữ 'p' đọc là:", questionType: "fill_blank", options: [], correctAnswer: "pờ", points: 1 },
      { questionText: "Trong các chữ sau, chữ nào là phụ âm?", questionType: "multiple_choice", options: ["A. u", "B. i", "C. h", "D. e"], correctAnswer: "C", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "ngu-van",
    chapter: "chuong-2",
    chapterName: "Vần và tiếng",
    title: "Kiểm tra Vần và tiếng",
    description: "Bài kiểm tra nhận biết vần, ghép vần và đánh vần tiếng",
    duration: 20,
    questions: [
      { questionText: "Từ nào có vần 'an'?", questionType: "multiple_choice", options: ["A. Bàn", "B. Bạn", "C. Cả Bàn và Bạn", "D. Bún"], correctAnswer: "C", points: 1 },
      { questionText: "Điền vần thích hợp: c... + an = ...?", questionType: "fill_blank", options: [], correctAnswer: "can", points: 1 },
      { questionText: "Từ 'mẹ' có mấy tiếng?", questionType: "fill_blank", options: [], correctAnswer: "1", points: 1 },
      { questionText: "Từ nào có vần 'ang'?", questionType: "multiple_choice", options: ["A. Càng", "B. Cần", "C. Cầm", "D. Cằm"], correctAnswer: "A", points: 1 },
      { questionText: "Tìm từ có vần 'ăm':", questionType: "multiple_choice", options: ["A. Căm", "B. Cam", "C. Càm", "D. Cầm"], correctAnswer: "A", points: 1 },
      { questionText: "Từ 'bàn ghế' có mấy tiếng?", questionType: "fill_blank", options: [], correctAnswer: "2", points: 1 },
      { questionText: "Điền vần: m... + ang = ...?", questionType: "fill_blank", options: [], correctAnswer: "mang", points: 1 },
      { questionText: "Tiếng 'con' gồm âm đầu và vần nào?", questionType: "multiple_choice", options: ["A. Âm 'c' + vần 'on'", "B. Âm 'co' + vần 'n'", "C. Âm 'c' + vần 'ơn'", "D. Âm 'c' + vần 'o'"], correctAnswer: "A", points: 1 },
      { questionText: "Từ nào có vần 'ôn'?", questionType: "multiple_choice", options: ["A. Con", "B. Còn", "C. Côn", "D. Cả B và C"], correctAnswer: "D", points: 1 },
      { questionText: "Đánh vần tiếng 'mưa':", questionType: "fill_blank", options: [], correctAnswer: "m - ưa - mưa", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "ngu-van",
    chapter: "chuong-3",
    chapterName: "Tập viết và làm câu",
    title: "Kiểm tra Tập viết và làm câu",
    description: "Bài kiểm tra kỹ năng viết chữ, viết hoa và tạo câu đơn giản",
    duration: 20,
    questions: [
      { questionText: "Câu nào viết đúng chính tả?", questionType: "multiple_choice", options: ["A. Con mèo đang ngủ.", "B. con mèo đang ngủ.", "C. Con Mèo đang ngủ.", "D. con Mèo đang Ngủ."], correctAnswer: "A", points: 1 },
      { questionText: "Chữ nào phải viết hoa trong câu: 'hà nội là thủ đô'?", questionType: "fill_blank", options: [], correctAnswer: "H", points: 1 },
      { questionText: "Dấu chấm đặt ở đâu trong câu?", questionType: "multiple_choice", options: ["A. Đầu câu", "B. Giữa câu", "C. Cuối câu", "D. Trước từ"], correctAnswer: "C", points: 1 },
      { questionText: "Viết lại cho đúng: 'bạn tên là gì'", questionType: "fill_blank", options: [], correctAnswer: "Bạn tên là gì?", points: 1 },
      { questionText: "Từ chỉ người trong câu: 'Mẹ đi chợ' là:", questionType: "multiple_choice", options: ["A. Mẹ", "B. Đi", "C. Chợ", "D. Mẹ đi"], correctAnswer: "A", points: 1 },
      { questionText: "Từ chỉ hoạt động trong câu: 'Em đi học' là:", questionType: "multiple_choice", options: ["A. Em", "B. Đi học", "C. Học", "D. Đi"], correctAnswer: "B", points: 1 },
      { questionText: "Câu hỏi kết thúc bằng dấu gì?", questionType: "multiple_choice", options: ["A. Dấu chấm", "B. Dấu chấm than", "C. Dấu chấm hỏi", "D. Dấu phẩy"], correctAnswer: "C", points: 1 },
      { questionText: "Chữ cái nào cần viết hoa ở đầu câu?", questionType: "fill_blank", options: [], correctAnswer: "chữ cái đầu tiên", points: 1 },
    ]
  },
  {
    grade: 1,
    subject: "ngu-van",
    chapter: "chuong-4",
    chapterName: "Đọc hiểu đoạn văn ngắn",
    title: "Kiểm tra Đọc hiểu đoạn văn ngắn",
    description: "Bài kiểm tra kỹ năng đọc hiểu đoạn văn ngắn, tìm ý chính",
    duration: 25,
    questions: [
      { questionText: "Đoạn văn thường bắt đầu bằng gì?", questionType: "multiple_choice", options: ["A. Dấu chấm than", "B. Chữ viết hoa", "C. Dấu phẩy", "D. Dấu chấm hỏi"], correctAnswer: "B", points: 1 },
      { questionText: "'Mẹ làm vườn. Mẹ trồng nhiều hoa. Hoa nở rất đẹp.' Đoạn văn trên kể về ai?", questionType: "fill_blank", options: [], correctAnswer: "Mẹ", points: 1 },
      { questionText: "Trong câu 'Con mèo đang ngủ', từ chỉ hoạt động là:", questionType: "multiple_choice", options: ["A. Con", "B. Mèo", "C. Đang", "D. Ngủ"], correctAnswer: "D", points: 1 },
      { questionText: "Đọc đoạn: 'Bé Lan đi học. Bé mang theo cặp sách.' Bé Lan mang theo gì?", questionType: "multiple_choice", options: ["A. Bút chì", "B. Cặp sách", "C. Sổ tay", "D. Bánh kẹo"], correctAnswer: "B", points: 1 },
      { questionText: "Từ chỉ sự vật trong câu 'Bông hoa rất đẹp' là:", questionType: "fill_blank", options: [], correctAnswer: "bông hoa", points: 1 },
      { questionText: "Câu kể kết thúc bằng dấu gì?", questionType: "multiple_choice", options: ["A. Dấu chấm hỏi", "B. Dấu chấm than", "C. Dấu chấm", "D. Dấu phẩy"], correctAnswer: "C", points: 1 },
      { questionText: "'Trời đang mưa. Gió thổi mạnh.' Đoạn văn nói về điều gì?", questionType: "multiple_choice", options: ["A. Trời nắng", "B. Trời mưa và gió", "C. Trời lạnh", "D. Trời khô"], correctAnswer: "B", points: 1 },
      { questionText: "Từ 'rất' trong câu 'Bông hoa rất đẹp' dùng để:", questionType: "fill_blank", options: [], correctAnswer: "nhấn mạnh", points: 1 },
      { questionText: "Đọc đoạn: 'Mùa xuân, cây đơm hoa. Hoa màu trắng.' Hoa màu gì?", questionType: "fill_blank", options: [], correctAnswer: "trắng", points: 1 },
      { questionText: "Câu cảm thán dùng để làm gì?", questionType: "multiple_choice", options: ["A. Hỏi thông tin", "B. Kể chuyện", "C. Bày tỏ cảm xúc", "D. Ra lệnh"], correctAnswer: "C", points: 1 },
    ]
  },

  // ===== LỚP 2 - TOÁN =====
  {
    grade: 2,
    subject: "toan",
    chapter: "chuong-1",
    chapterName: "Các số đến 100",
    title: "Kiểm tra Các số đến 100",
    description: "Bài kiểm tra kiến thức về các số trong phạm vi 100",
    duration: 25,
    questions: [
      { questionText: "Số 56 gồm mấy chục và mấy đơn vị?", questionType: "multiple_choice", options: ["A. 5 chục và 6 đơn vị", "B. 6 chục và 5 đơn vị", "C. 56 chục", "D. 50 chục và 6 đơn vị"], correctAnswer: "A", points: 1 },
      { questionText: "Số liền sau số 99 là:", questionType: "fill_blank", options: [], correctAnswer: "100", points: 1 },
      { questionText: "Số lớn nhất có 2 chữ số là:", questionType: "multiple_choice", options: ["A. 90", "B. 99", "C. 100", "D. 89"], correctAnswer: "B", points: 1 },
      { questionText: "Viết số từ nhỏ đến lớn: 45, 23, 67, 12", questionType: "fill_blank", options: [], correctAnswer: "12 23 45 67", points: 1 },
      { questionText: "So sánh: 45 ... 54", questionType: "multiple_choice", options: ["A. > ", "B. <", "C. =", "D. Không so sánh được"], correctAnswer: "B", points: 1 },
      { questionText: "Số 70 gồm mấy chục?", questionType: "fill_blank", options: [], correctAnswer: "7", points: 1 },
      { questionText: "Số nào nằm giữa 34 và 36?", questionType: "fill_blank", options: [], correctAnswer: "35", points: 1 },
      { questionText: "40 + 30 = ?", questionType: "multiple_choice", options: ["A. 60", "B. 70", "C. 80", "D. 43"], correctAnswer: "B", points: 1 },
      { questionText: "85 - 5 = ?", questionType: "fill_blank", options: [], correctAnswer: "80", points: 1 },
      { questionText: "Đếm thêm 5: 25, 30, ..., 40", questionType: "fill_blank", options: [], correctAnswer: "35", points: 1 },
    ]
  },
  {
    grade: 2,
    subject: "toan",
    chapter: "chuong-2",
    chapterName: "Phép cộng trừ trong phạm vi 100",
    title: "Kiểm tra Phép cộng trừ phạm vi 100",
    description: "Bài kiểm tra kỹ năng cộng trừ các số trong phạm vi 100",
    duration: 30,
    questions: [
      { questionText: "36 + 24 = ?", questionType: "multiple_choice", options: ["A. 50", "B. 60", "C. 70", "D. 56"], correctAnswer: "B", points: 1 },
      { questionText: "82 - 37 = ?", questionType: "fill_blank", options: [], correctAnswer: "45", points: 1 },
      { questionText: "47 + 28 = ?", questionType: "multiple_choice", options: ["A. 65", "B. 75", "C. 85", "D. 74"], correctAnswer: "B", points: 1 },
      { questionText: "100 - 46 = ?", questionType: "fill_blank", options: [], correctAnswer: "54", points: 1 },
      { questionText: "Tìm x: x + 35 = 72", questionType: "fill_blank", options: [], correctAnswer: "37", points: 1 },
      { questionText: "Tìm x: 91 - x = 48", questionType: "fill_blank", options: [], correctAnswer: "43", points: 1 },
      { questionText: "Lớp 2A có 35 học sinh, lớp 2B có 32 học sinh. Hỏi cả hai lớp có bao nhiêu học sinh?", questionType: "multiple_choice", options: ["A. 65 học sinh", "B. 67 học sinh", "C. 77 học sinh", "D. 63 học sinh"], correctAnswer: "B", points: 1 },
      { questionText: "53 + 19 = ?", questionType: "fill_blank", options: [], correctAnswer: "72", points: 1 },
      { questionText: "Cửa hàng có 85 kg gạo, bán đi 47 kg. Hỏi còn lại bao nhiêu kg gạo?", questionType: "fill_blank", options: [], correctAnswer: "38", points: 1 },
      { questionText: "64 - 28 = ?", questionType: "multiple_choice", options: ["A. 36", "B. 46", "C. 26", "D. 34"], correctAnswer: "A", points: 1 },
    ]
  },
  {
    grade: 2,
    subject: "toan",
    chapter: "chuong-3",
    chapterName: "Phép nhân và bảng nhân",
    title: "Kiểm tra Phép nhân",
    description: "Bài kiểm tra kiến thức về phép nhân và bảng nhân",
    duration: 25,
    questions: [
      { questionText: "2 × 5 = ?", questionType: "multiple_choice", options: ["A. 7", "B. 10", "C. 8", "D. 12"], correctAnswer: "B", points: 1 },
      { questionText: "3 × 4 = ?", questionType: "fill_blank", options: [], correctAnswer: "12", points: 1 },
      { questionText: "5 × 5 = ?", questionType: "multiple_choice", options: ["A. 20", "B. 30", "C. 25", "D. 15"], correctAnswer: "C", points: 1 },
      { questionText: "4 × 6 = ?", questionType: "fill_blank", options: [], correctAnswer: "24", points: 1 },
      { questionText: "Mỗi hàng có 5 cái kẹo, có 3 hàng. Hỏi có tất cả mấy cái kẹo?", questionType: "multiple_choice", options: ["A. 8 cái", "B. 15 cái", "C. 10 cái", "D. 20 cái"], correctAnswer: "B", points: 1 },
      { questionText: "2 × 7 = ?", questionType: "fill_blank", options: [], correctAnswer: "14", points: 1 },
      { questionText: "5 × ... = 35. Số cần điền là?", questionType: "fill_blank", options: [], correctAnswer: "7", points: 1 },
      { questionText: "3 × 3 = ?", questionType: "multiple_choice", options: ["A. 6", "B. 9", "C. 12", "D. 8"], correctAnswer: "B", points: 1 },
      { questionText: "4 × 5 + 3 = ?", questionType: "fill_blank", options: [], correctAnswer: "23", points: 1 },
      { questionText: "Nhân số nào với 2 thì bằng 16?", questionType: "fill_blank", options: [], correctAnswer: "8", points: 1 },
    ]
  },
  {
    grade: 2,
    subject: "toan",
    chapter: "chuong-4",
    chapterName: "Đường thẳng, góc, hình chữ nhật, hình vuông",
    title: "Kiểm tra Đường thẳng, góc, hình chữ nhật, hình vuông",
    description: "Bài kiểm tra kiến thức về đường thẳng, góc và hình học",
    duration: 25,
    questions: [
      { questionText: "Hình chữ nhật có mấy cạnh đối bằng nhau?", questionType: "multiple_choice", options: ["A. 1 cặp", "B. 2 cặp", "C. 3 cặp", "D. 4 cặp"], correctAnswer: "B", points: 1 },
      { questionText: "Chu vi hình vuông cạnh 5 cm là:", questionType: "fill_blank", options: [], correctAnswer: "20 cm", points: 1 },
      { questionText: "Góc vuông có số đo bằng:", questionType: "multiple_choice", options: ["A. 90°", "B. 45°", "C. 180°", "D. 60°"], correctAnswer: "A", points: 1 },
      { questionText: "Chu vi hình chữ nhật dài 6 cm, rộng 4 cm là:", questionType: "fill_blank", options: [], correctAnswer: "20 cm", points: 1 },
      { questionText: "Hình vuông cạnh 3 cm có chu vi là:", questionType: "multiple_choice", options: ["A. 6 cm", "B. 9 cm", "C. 12 cm", "D. 3 cm"], correctAnswer: "C", points: 1 },
      { questionText: "Đường thẳng phân giác của đoạn thẳng là đường thẳng đi qua:", questionType: "multiple_choice", options: ["A. Đầu mút", "B. Trung điểm và vuông góc", "C. Một điểm bất kỳ", "D. Hai đầu mút"], correctAnswer: "B", points: 1 },
      { questionText: "Hình chữ nhật có mấy góc vuông?", questionType: "fill_blank", options: [], correctAnswer: "4", points: 1 },
      { questionText: "Để vẽ góc vuông, em dùng dụng cụ gì?", questionType: "fill_blank", options: [], correctAnswer: "ê-ke", points: 1 },
    ]
  },
  {
    grade: 2,
    subject: "toan",
    chapter: "chuong-5",
    chapterName: "Đại lượng và đo đại lượng",
    title: "Kiểm tra Đại lượng và đo đại lượng",
    description: "Bài kiểm tra kiến thức về các đơn vị đo độ dài, khối lượng, thời gian",
    duration: 25,
    questions: [
      { questionText: "1 mét bằng bao nhiêu đề-xi-mét?", questionType: "multiple_choice", options: ["A. 10 dm", "B. 100 dm", "C. 5 dm", "D. 20 dm"], correctAnswer: "A", points: 1 },
      { questionText: "1 kg = ? g", questionType: "fill_blank", options: [], correctAnswer: "1000", points: 1 },
      { questionText: "Nửa giờ bằng bao nhiêu phút?", questionType: "multiple_choice", options: ["A. 15 phút", "B. 20 phút", "C. 30 phút", "D. 45 phút"], correctAnswer: "C", points: 1 },
      { questionText: "1 dm = ? cm", questionType: "fill_blank", options: [], correctAnswer: "10", points: 1 },
      { questionText: "Để đo khối lượng một bao gạo, em dùng đơn vị:", questionType: "multiple_choice", options: ["A. Xăng-ti-mét", "B. Lít", "C. Kilôgam", "D. Phút"], correctAnswer: "C", points: 1 },
      { questionText: "8 dm 5 cm = ? cm", questionType: "fill_blank", options: [], correctAnswer: "85", points: 1 },
      { questionText: "Từ 7 giờ sáng đến 9 giờ sáng là bao lâu?", questionType: "multiple_choice", options: ["A. 1 giờ", "B. 2 giờ", "C. 3 giờ", "D. 4 giờ"], correctAnswer: "B", points: 1 },
      { questionText: "Sợi dây dài 2 m, cắt đi 50 cm. Còn lại bao nhiêu xăng-ti-mét?", questionType: "fill_blank", options: [], correctAnswer: "150", points: 1 },
    ]
  },

  // ===== LỚP 2 - NGỮ VĂN =====
  {
    grade: 2,
    subject: "ngu-van",
    chapter: "chuong-1",
    chapterName: "Đọc hiểu văn bản ngắn",
    title: "Kiểm tra Đọc hiểu văn bản ngắn",
    description: "Bài kiểm tra kỹ năng đọc và hiểu văn bản ngắn, tìm ý chính",
    duration: 25,
    questions: [
      { questionText: "Trong câu 'Con mèo đang ngủ trên ghế', từ chỉ sự vật là:", questionType: "multiple_choice", options: ["A. đang", "B. ngủ", "C. mèo, ghế", "D. trên"], correctAnswer: "C", points: 1 },
      { questionText: "Từ trái nghĩa với 'cao' là:", questionType: "fill_blank", options: [], correctAnswer: "thấp", points: 1 },
      { questionText: "Từ đồng nghĩa với 'đẹp' là:", questionType: "multiple_choice", options: ["A. Xấu", "B. Xinh", "C. To", "D. Nhỏ"], correctAnswer: "B", points: 1 },
      { questionText: "Câu nào là câu hỏi?", questionType: "multiple_choice", options: ["A. Hôm nay trời nắng.", "B. Bạn đi học chứ?", "C. Chào cô giáo!", "D. Mẹ yêu lắm."], correctAnswer: "B", points: 1 },
      { questionText: "Từ 'hoa hồng' thuộc nhóm từ nào?", questionType: "multiple_choice", options: ["A. Đồ vật", "B. Động vật", "C. Thực vật", "D. Con người"], correctAnswer: "C", points: 1 },
      { questionText: "Dấu phẩy dùng để làm gì?", questionType: "multiple_choice", options: ["A. Kết thúc câu", "B. Ngắt nghỉ ngắn trong câu", "C. Hỏi câu", "D. Bày tỏ cảm xúc"], correctAnswer: "B", points: 1 },
      { questionText: "Từ nào chỉ hoạt động trong câu 'Bé ăn cơm'?", questionType: "fill_blank", options: [], correctAnswer: "ăn", points: 1 },
      { questionText: "Đoạn văn có mấy câu? 'Mẹ đi chợ. Mẹ mua cá. Mẹ mua rau.'", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "Câu cảm thán kết thúc bằng dấu gì?", questionType: "multiple_choice", options: ["A. Dấu chấm", "B. Dấu chấm hỏi", "C. Dấu chấm than", "D. Dấu hai chấm"], correctAnswer: "C", points: 1 },
      { questionText: "Từ nào chỉ đặc điểm trong câu 'Quả cam ngọt'?", questionType: "fill_blank", options: [], correctAnswer: "ngọt", points: 1 },
    ]
  },
  {
    grade: 2,
    subject: "ngu-van",
    chapter: "chuong-2",
    chapterName: "Chính tả và Luyện từ và câu",
    title: "Kiểm tra Chính tả và Luyện từ và câu",
    description: "Bài kiểm tra chính tả, từ loại cơ bản và đặt câu",
    duration: 25,
    questions: [
      { questionText: "Từ nào viết đúng chính tả?", questionType: "multiple_choice", options: ["A. Ngon lành", "B. Chuyền cợt", "C. Sáng sủa", "D. Xanh xao"], correctAnswer: "C", points: 1 },
      { questionText: "Điền 'ch' hay 'tr': ...ời nở", questionType: "fill_blank", options: [], correctAnswer: "tr", points: 1 },
      { questionText: "Điền 's' hay 'x': ...uống nước", questionType: "fill_blank", options: [], correctAnswer: "x", points: 1 },
      { questionText: "Từ nào sai chính tả?", questionType: "multiple_choice", options: ["A. Sáng sủa", "B. Xinh đẹp", "C. Trống vắng", "D. Chười cợt"], correctAnswer: "D", points: 1 },
      { questionText: "Điền 'g' hay 'gh': ...ế gỗ", questionType: "fill_blank", options: [], correctAnswer: "gh", points: 1 },
      { questionText: "Từ nào có tiếng chứa vần 'ương'?", questionType: "multiple_choice", options: ["A. Sương", "B. Sóng", "C. Sông", "D. Son"], correctAnswer: "A", points: 1 },
      { questionText: "Điền dấu hỏi hay dấu ngã: Bạn cũ hay ...?", questionType: "fill_blank", options: [], correctAnswer: "cũ", points: 1 },
      { questionText: "Từ 'chạy' là từ chỉ gì?", questionType: "multiple_choice", options: ["A. Sự vật", "B. Đặc điểm", "C. Hoạt động", "D. Số lượng"], correctAnswer: "C", points: 1 },
      { questionText: "Câu kể Ai làm gì? có dạng:", questionType: "multiple_choice", options: ["A. Ai là gì?", "B. Ai làm gì?", "C. Ai thế nào?", "D. Ai ở đâu?"], correctAnswer: "B", points: 1 },
      { questionText: "Tìm từ chứa tiếng có vần 'oai':", questionType: "multiple_choice", options: ["A. Quạt", "B. Giỏi", "C. Khoai", "D. Loa"], correctAnswer: "C", points: 1 },
    ]
  },
  {
    grade: 2,
    subject: "ngu-van",
    chapter: "chuong-3",
    chapterName: "Tập làm văn - Viết đoạn văn",
    title: "Kiểm tra Tập làm văn - Viết đoạn văn",
    description: "Bài kiểm tra kỹ năng viết đoạn văn ngắn về một sự vật, hiện tượng",
    duration: 25,
    questions: [
      { questionText: "Đoạn văn thường gồm mấy câu trở lên?", questionType: "multiple_choice", options: ["A. 1 câu", "B. 2 câu trở lên", "C. 5 câu trở lên", "D. 10 câu"], correctAnswer: "B", points: 1 },
      { questionText: "Khi viết đoạn văn tả con vật, em cần nói về:", questionType: "multiple_choice", options: ["A. Chỉ màu sắc", "B. Chỉ hình dáng", "C. Hình dáng, màu sắc, thói quen...", "D. Chỉ thói quen"], correctAnswer: "C", points: 1 },
      { questionText: "Câu mở đoạn thường làm nhiệm vụ gì?", questionType: "multiple_choice", options: ["A. Kết thúc đoạn", "B. Nêu ý chính của đoạn", "C. Hỏi câu hỏi", "D. Bày tỏ cảm xúc"], correctAnswer: "B", points: 1 },
      { questionText: "Viết câu mở đoạn cho bài tả cái bút chì:", questionType: "fill_blank", options: [], correctAnswer: "Chiếc bút chì của em rất đẹp.", points: 1 },
      { questionText: "Đoạn văn cần viết liên tục, không cần:", questionType: "multiple_choice", options: ["A. Dấu chấm", "B. Chữ viết hoa", "C. Chuyển dòng xuống đoạn mới", "D. Từ ngữ gợi tả"], correctAnswer: "C", points: 1 },
      { questionText: "Từ gợi tả hình dáng trong câu 'Con mèo lông trắng mượt mà' là:", questionType: "fill_blank", options: [], correctAnswer: "mượt mà", points: 1 },
      { questionText: "Khi viết đoạn văn tả loài hoa, em nên bắt đầu bằng:", questionType: "multiple_choice", options: ["A. Giới thiệu tên loài hoa", "B. Tả màu hoa", "C. Tả hương hoa", "D. Nêu cảm nghĩ"], correctAnswer: "A", points: 1 },
      { questionText: "Dấu chấm than dùng trong câu:", questionType: "fill_blank", options: [], correctAnswer: "câu cảm thán", points: 1 },
    ]
  },

  // ===== LỚP 3 - TOÁN =====
  {
    grade: 3,
    subject: "toan",
    chapter: "chuong-1",
    chapterName: "Ôn tập và bổ sung các số đến 1000. Phép cộng trừ",
    title: "Kiểm tra Ôn tập và bổ sung các số đến 1000. Phép cộng trừ",
    description: "Bài kiểm tra kỹ năng cộng trừ các số trong phạm vi 1000",
    duration: 30,
    questions: [
      { questionText: "345 + 278 = ?", questionType: "multiple_choice", options: ["A. 623", "B. 523", "C. 613", "D. 723"], correctAnswer: "A", points: 1 },
      { questionText: "812 - 456 = ?", questionType: "fill_blank", options: [], correctAnswer: "356", points: 1 },
      { questionText: "Tìm x: x + 234 = 567", questionType: "fill_blank", options: [], correctAnswer: "333", points: 1 },
      { questionText: "500 + 300 = ?", questionType: "multiple_choice", options: ["A. 700", "B. 800", "C. 900", "D. 600"], correctAnswer: "B", points: 1 },
      { questionText: "999 - 456 = ?", questionType: "fill_blank", options: [], correctAnswer: "543", points: 1 },
      { questionText: "456 + 234 + 100 = ?", questionType: "multiple_choice", options: ["A. 790", "B. 890", "C. 780", "D. 800"], correctAnswer: "A", points: 1 },
      { questionText: "Cửa hàng có 525 kg gạo, bán đi 237 kg. Hỏi còn lại bao nhiêu kg gạo?", questionType: "fill_blank", options: [], correctAnswer: "288", points: 1 },
      { questionText: "Số lớn nhất có 3 chữ số là:", questionType: "fill_blank", options: [], correctAnswer: "999", points: 1 },
      { questionText: "678 + ... = 900. Số cần điền là?", questionType: "fill_blank", options: [], correctAnswer: "222", points: 1 },
      { questionText: "1000 - 357 = ?", questionType: "multiple_choice", options: ["A. 743", "B. 643", "C. 653", "D. 753"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 3,
    subject: "toan",
    chapter: "chuong-2",
    chapterName: "Phép nhân",
    title: "Kiểm tra Phép nhân",
    description: "Bài kiểm tra kỹ năng nhân các số",
    duration: 30,
    questions: [
      { questionText: "23 × 4 = ?", questionType: "multiple_choice", options: ["A. 82", "B. 92", "C. 86", "D. 96"], correctAnswer: "B", points: 1 },
      { questionText: "15 × 5 = ?", questionType: "fill_blank", options: [], correctAnswer: "75", points: 1 },
      { questionText: "Mỗi túi có 12 cái kẹo, có 6 túi. Hỏi có tất cả mấy cái kẹo?", questionType: "multiple_choice", options: ["A. 60 cái", "B. 72 cái", "C. 78 cái", "D. 66 cái"], correctAnswer: "B", points: 1 },
      { questionText: "125 × 3 = ?", questionType: "fill_blank", options: [], correctAnswer: "375", points: 1 },
      { questionText: "Nhân số nào với 7 thì bằng 56?", questionType: "fill_blank", options: [], correctAnswer: "8", points: 1 },
      { questionText: "24 × 5 = ?", questionType: "multiple_choice", options: ["A. 100", "B. 110", "C. 120", "D. 130"], correctAnswer: "C", points: 1 },
      { questionText: "32 × 3 + 15 = ?", questionType: "fill_blank", options: [], correctAnswer: "111", points: 1 },
      { questionText: "Một lớp có 35 học sinh, mỗi học sinh được phát 4 quyển vở. Hỏi cần bao nhiêu quyển vở?", questionType: "fill_blank", options: [], correctAnswer: "140", points: 1 },
      { questionText: "0 × 123 = ?", questionType: "multiple_choice", options: ["A. 123", "B. 0", "C. 1", "D. 12"], correctAnswer: "B", points: 1 },
      { questionText: "45 × 2 = ?", questionType: "fill_blank", options: [], correctAnswer: "90", points: 1 },
    ]
  },
  {
    grade: 3,
    subject: "toan",
    chapter: "chuong-3",
    chapterName: "Phép chia",
    title: "Kiểm tra Phép chia",
    description: "Bài kiểm tra kỹ năng chia các số",
    duration: 30,
    questions: [
      { questionText: "36 ÷ 4 = ?", questionType: "multiple_choice", options: ["A. 8", "B. 9", "C. 7", "D. 6"], correctAnswer: "B", points: 1 },
      { questionText: "45 ÷ 5 = ?", questionType: "fill_blank", options: [], correctAnswer: "9", points: 1 },
      { questionText: "Có 24 cái kẹo chia đều cho 6 bạn. Mỗi bạn được mấy cái kẹo?", questionType: "multiple_choice", options: ["A. 3 cái", "B. 4 cái", "C. 5 cái", "D. 6 cái"], correctAnswer: "B", points: 1 },
      { questionText: "72 ÷ 8 = ?", questionType: "fill_blank", options: [], correctAnswer: "9", points: 1 },
      { questionText: "56 ÷ 7 = ?", questionType: "fill_blank", options: [], correctAnswer: "8", points: 1 },
      { questionText: "100 ÷ 10 = ?", questionType: "multiple_choice", options: ["A. 5", "B. 10", "C. 15", "D. 20"], correctAnswer: "B", points: 1 },
      { questionText: "48 ÷ 6 = ?", questionType: "fill_blank", options: [], correctAnswer: "8", points: 1 },
      { questionText: "Có 35 quyển sách xếp đều vào 7 ngăn. Mỗi ngăn có mấy quyển sách?", questionType: "fill_blank", options: [], correctAnswer: "5", points: 1 },
      { questionText: "81 ÷ 9 = ?", questionType: "fill_blank", options: [], correctAnswer: "9", points: 1 },
      { questionText: "64 ÷ 8 = ?", questionType: "multiple_choice", options: ["A. 7", "B. 9", "C. 8", "D. 6"], correctAnswer: "C", points: 1 },
    ]
  },
  {
    grade: 3,
    subject: "toan",
    chapter: "chuong-4",
    chapterName: "Hình bình hành, hình thoi. Chu vi, diện tích",
    title: "Kiểm tra Hình học và diện tích",
    description: "Bài kiểm tra kiến thức về hình bình hành, hình thoi, chu vi và diện tích",
    duration: 30,
    questions: [
      { questionText: "Hình bình hành có mấy cặp cạnh đối song song?", questionType: "multiple_choice", options: ["A. 1 cặp", "B. 2 cặp", "C. 3 cặp", "D. 0 cặp"], correctAnswer: "B", points: 1 },
      { questionText: "Diện tích hình chữ nhật được tính bằng công thức:", questionType: "multiple_choice", options: ["A. Dài + Rộng", "B. Dài × Rộng", "C. (Dài + Rộng) × 2", "D. Dài × 2"], correctAnswer: "B", points: 1 },
      { questionText: "Diện tích hình vuông cạnh 5 cm là:", questionType: "fill_blank", options: [], correctAnswer: "25 cm2", points: 1 },
      { questionText: "Chu vi hình chữ nhật dài 8 cm, rộng 5 cm là:", questionType: "fill_blank", options: [], correctAnswer: "26 cm", points: 1 },
      { questionText: "Hình thoi có mấy cạnh bằng nhau?", questionType: "multiple_choice", options: ["A. 2", "B. 3", "C. 4", "D. 0"], correctAnswer: "C", points: 1 },
      { questionText: "Diện tích hình chữ nhật dài 10 cm, rộng 6 cm là:", questionType: "fill_blank", options: [], correctAnswer: "60 cm2", points: 1 },
      { questionText: "Chu vi hình vuông cạnh 7 cm là:", questionType: "multiple_choice", options: ["A. 14 cm", "B. 28 cm", "C. 49 cm", "D. 21 cm"], correctAnswer: "B", points: 1 },
      { questionText: "Đơn vị đo diện tích là:", questionType: "multiple_choice", options: ["A. cm", "B. cm2", "C. kg", "D. lít"], correctAnswer: "B", points: 1 },
      { questionText: "Một hình chữ nhật có diện tích 24 cm2, chiều dài 8 cm. Chiều rộng là:", questionType: "fill_blank", options: [], correctAnswer: "3 cm", points: 1 },
      { questionText: "Hình bình hành có đặc điểm nào sau đây?", questionType: "multiple_choice", options: ["A. Bốn cạnh bằng nhau", "B. Hai cặp cạnh đối song song và bằng nhau", "C. Bốn góc vuông", "D. Không có cạnh song song"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 3,
    subject: "toan",
    chapter: "chuong-5",
    chapterName: "Giờ, phút, giây. Bảng đơn vị đo độ dài",
    title: "Kiểm tra Đại lượng và đo đại lượng",
    description: "Bài kiểm tra kiến thức về thời gian và các đơn vị đo độ dài",
    duration: 25,
    questions: [
      { questionText: "1 giờ = ? phút", questionType: "fill_blank", options: [], correctAnswer: "60", points: 1 },
      { questionText: "1 phút = ? giây", questionType: "multiple_choice", options: ["A. 10 giây", "B. 30 giây", "C. 60 giây", "D. 100 giây"], correctAnswer: "C", points: 1 },
      { questionText: "1 km = ? m", questionType: "fill_blank", options: [], correctAnswer: "1000", points: 1 },
      { questionText: "1 m = ? cm", questionType: "fill_blank", options: [], correctAnswer: "100", points: 1 },
      { questionText: "Từ 8 giờ 30 phút đến 9 giờ 15 phút là bao lâu?", questionType: "multiple_choice", options: ["A. 30 phút", "B. 45 phút", "C. 1 giờ 15 phút", "D. 45 phút"], correctAnswer: "B", points: 1 },
      { questionText: "3 km 200 m = ? m", questionType: "fill_blank", options: [], correctAnswer: "3200", points: 1 },
      { questionText: "Quãng đường AB dài 5 km 400 m, quãng đường BC dài 2 km 600 m. Quãng đường AC dài bao nhiêu?", questionType: "fill_blank", options: [], correctAnswer: "8 km", points: 1 },
      { questionText: "Đơn vị đo độ dài nào lớn nhất?", questionType: "multiple_choice", options: ["A. mm", "B. cm", "C. m", "D. km"], correctAnswer: "D", points: 1 },
    ]
  },

  // ===== LỚP 3 - NGỮ VĂN =====
  {
    grade: 3,
    subject: "ngu-van",
    chapter: "chuong-1",
    chapterName: "Đọc hiểu văn bản",
    title: "Kiểm tra Đọc hiểu văn bản",
    description: "Bài kiểm tra kỹ năng đọc hiểu văn bản dài hơn, tìm ý chính và chi tiết",
    duration: 30,
    questions: [
      { questionText: "'Bầu trời mùa thu xanh cao' - Câu này tả điều gì?", questionType: "multiple_choice", options: ["A. Tả cây", "B. Tả bầu trời", "C. Tả nước", "D. Tả đất"], correctAnswer: "B", points: 1 },
      { questionText: "Từ 'rực rỡ' có nghĩa là:", questionType: "multiple_choice", options: ["A. Tối tăm", "B. Tỏa sáng lung linh", "C. Nhỏ bé", "D. Buồn bã"], correctAnswer: "B", points: 1 },
      { questionText: "Câu kể là câu dùng để:", questionType: "multiple_choice", options: ["A. Hỏi", "B. Kể, thông báo điều gì", "C. Kêu gọi", "D. Bày tỏ cảm xúc"], correctAnswer: "B", points: 1 },
      { questionText: "Từ chỉ đặc điểm trong câu 'Bông hoa hồng rất đẹp' là:", questionType: "fill_blank", options: [], correctAnswer: "đẹp", points: 1 },
      { questionText: "Từ trái nghĩa với 'buồn' là:", questionType: "fill_blank", options: [], correctAnswer: "vui", points: 1 },
      { questionText: "Trong câu 'Mẹ nấu cơm rất ngon', từ chỉ hoạt động là:", questionType: "multiple_choice", options: ["A. Mẹ", "B. Nấu", "C. Cơm", "D. Ngon"], correctAnswer: "B", points: 1 },
      { questionText: "Câu cảm thán kết thúc bằng dấu gì?", questionType: "multiple_choice", options: ["A. Dấu chấm", "B. Dấu hỏi", "C. Dấu chấm than", "D. Dấu phẩy"], correctAnswer: "C", points: 1 },
      { questionText: "Từ đồng nghĩa với 'xinh đẹp' là:", questionType: "fill_blank", options: [], correctAnswer: "đẹp đẽ", points: 1 },
      { questionText: "Nội dung chính của đoạn văn là:", questionType: "multiple_choice", options: ["A. Ý quan trọng nhất được nói đến", "B. Chi tiết phụ", "C. Tên bài", "D. Tên tác giả"], correctAnswer: "A", points: 1 },
      { questionText: "Để hiểu nội dung đoạn văn, em cần:", questionType: "fill_blank", options: [], correctAnswer: "đọc kỹ", points: 1 },
    ]
  },
  {
    grade: 3,
    subject: "ngu-van",
    chapter: "chuong-2",
    chapterName: "Luyện từ và câu",
    title: "Kiểm tra Luyện từ và câu",
    description: "Bài kiểm tra kiến thức về danh từ, động từ, tính từ và các kiểu câu",
    duration: 25,
    questions: [
      { questionText: "Danh từ là từ chỉ:", questionType: "multiple_choice", options: ["A. Hoạt động", "B. Đặc điểm", "C. Sự vật, hiện tượng", "D. Số lượng"], correctAnswer: "C", points: 1 },
      { questionText: "Động từ là từ chỉ:", questionType: "fill_blank", options: [], correctAnswer: "hoạt động", points: 1 },
      { questionText: "Tính từ là từ chỉ:", questionType: "multiple_choice", options: ["A. Sự vật", "B. Hoạt động", "C. Đặc điểm, tính chất", "D. Số lượng"], correctAnswer: "C", points: 1 },
      { questionText: "Trong câu 'Chiếc áo đỏ rất đẹp', từ 'đỏ' là:", questionType: "multiple_choice", options: ["A. Danh từ", "B. Động từ", "C. Tính từ", "D. Đại từ"], correctAnswer: "C", points: 1 },
      { questionText: "Câu kể Ai làm gì? có cấu trúc:", questionType: "multiple_choice", options: ["A. Ai + là gì", "B. Ai + làm gì", "C. Ai + thế nào", "D. Ai + ở đâu"], correctAnswer: "B", points: 1 },
      { questionText: "Câu 'Hoa hồng nở trong vườn.' có mấy danh từ?", questionType: "multiple_choice", options: ["A. 1", "B. 2", "C. 3", "D. 4"], correctAnswer: "B", points: 1 },
      { questionText: "Mở rộng câu: 'Em đi học.' bằng cách thêm từ chỉ thời gian:", questionType: "fill_blank", options: [], correctAnswer: "Sáng nay em đi học.", points: 1 },
      { questionText: "Đại từ xưng hô 'mình' dùng để chỉ:", questionType: "multiple_choice", options: ["A. Người khác", "B. Chính mình", "C. Nhiều người", "D. Vật"], correctAnswer: "B", points: 1 },
      { questionText: "Trong câu 'Con mèo trắng đang ngủ', từ 'trắng' là:", questionType: "fill_blank", options: [], correctAnswer: "tính từ", points: 1 },
      { questionText: "Câu kể Ai thế nào? có cấu trúc:", questionType: "multiple_choice", options: ["A. Ai + làm gì", "B. Ai + là gì", "C. Ai + thế nào", "D. Ai + ở đâu"], correctAnswer: "C", points: 1 },
    ]
  },
  {
    grade: 3,
    subject: "ngu-van",
    chapter: "chuong-3",
    chapterName: "Tập làm văn",
    title: "Kiểm tra Tập làm văn - Viết đoạn văn",
    description: "Bài kiểm tra kỹ năng viết đoạn văn theo các kiểu câu kể",
    duration: 25,
    questions: [
      { questionText: "Đoạn văn cần có:", questionType: "multiple_choice", options: ["A. Chỉ một câu", "B. Nhiều câu cùng nói về một ý", "C. Câu hỏi và câu trả lời", "D. Chỉ câu cảm thán"], correctAnswer: "B", points: 1 },
      { questionText: "Khi viết đoạn văn tả con vật, em nên tả theo thứ tự nào?", questionType: "multiple_choice", options: ["A. Tả chi tiết phụ trước, chi tiết chính sau", "B. Tả bao quát rồi đến chi tiết", "C. Tả thói quen trước, hình dáng sau", "D. Không cần thứ tự"], correctAnswer: "B", points: 1 },
      { questionText: "Câu mở đoạn trong bài tả cây cối thường nêu:", questionType: "fill_blank", options: [], correctAnswer: "giới thiệu tên cây", points: 1 },
      { questionText: "Để đoạn văn hay hơn, em nên dùng:", questionType: "multiple_choice", options: ["A. Chỉ danh từ", "B. Từ ngữ gợi tả, gợi cảm", "C. Chỉ động từ", "D. Chỉ số từ"], correctAnswer: "B", points: 1 },
      { questionText: "Khi viết đoạn văn kể lại một việc, em cần nêu:", questionType: "multiple_choice", options: ["A. Ai, làm gì, khi nào, ở đâu", "B. Chỉ ai", "C. Chỉ ở đâu", "D. Chỉ khi nào"], correctAnswer: "A", points: 1 },
      { questionText: "Viết câu mở đoạn cho bài tả con mèo:", questionType: "fill_blank", options: [], correctAnswer: "Nhà em có nuôi một con mèo.", points: 1 },
      { questionText: "Cuối đoạn văn tả con vật, em thường viết:", questionType: "multiple_choice", options: ["A. Câu hỏi", "B. Câu nêu cảm nghĩ", "C. Câu mệnh lệnh", "D. Câu cảm thán"], correctAnswer: "B", points: 1 },
      { questionText: "Các câu trong đoạn văn phải liên kết với nhau bằng:", questionType: "fill_blank", options: [], correctAnswer: "từ nối", points: 1 },
    ]
  },

  // ===== LỚP 4 - TOÁN =====
  {
    grade: 4,
    subject: "toan",
    chapter: "chuong-1",
    chapterName: "Các số đến 100000",
    title: "Kiểm tra Các số đến 100000",
    description: "Bài kiểm tra kiến thức về các số trong phạm vi 100000",
    duration: 30,
    questions: [
      { questionText: "Số 24567 đọc là:", questionType: "multiple_choice", options: ["A. Hai mươi bốn nghìn năm trăm sáu mươi bảy", "B. Hai mươi lăm nghìn bốn trăm sáu mươi bảy", "C. Hai mươi tư nghìn năm trăm sáu mươi bảy", "D. Hai mươi bốn nghìn năm trăm sáu mươi bảy"], correctAnswer: "D", points: 1 },
      { questionText: "Viết số: Ba mươi lăm nghìn hai trăm mười hai =", questionType: "fill_blank", options: [], correctAnswer: "35212", points: 1 },
      { questionText: "Giá trị chữ số 5 trong số 45678 là:", questionType: "multiple_choice", options: ["A. 5", "B. 50", "C. 500", "D. 5000"], correctAnswer: "D", points: 1 },
      { questionText: "Số lớn nhất có 5 chữ số là:", questionType: "fill_blank", options: [], correctAnswer: "99999", points: 1 },
      { questionText: "Làm tròn số 4567 đến hàng nghìn:", questionType: "multiple_choice", options: ["A. 4000", "B. 5000", "C. 4500", "D. 4600"], correctAnswer: "B", points: 1 },
      { questionText: "So sánh: 23456 ... 24356", questionType: "fill_blank", options: [], correctAnswer: "<", points: 1 },
      { questionText: "Số liền sau số 9999 là:", questionType: "fill_blank", options: [], correctAnswer: "10000", points: 1 },
      { questionText: "Phân tích số 34567 = ... + ... + ... + ... + ...", questionType: "multiple_choice", options: ["A. 30000 + 4000 + 500 + 60 + 7", "B. 3000 + 400 + 50 + 6 + 7", "C. 30000 + 4000 + 500 + 67", "D. 34000 + 567"], correctAnswer: "A", points: 1 },
      { questionText: "Hàng chục nghìn trong số 67890 có chữ số nào?", questionType: "fill_blank", options: [], correctAnswer: "6", points: 1 },
      { questionText: "Số nhỏ nhất có 5 chữ số khác nhau là:", questionType: "multiple_choice", options: ["A. 10000", "B. 10234", "C. 12345", "D. 11111"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 4,
    subject: "toan",
    chapter: "chuong-2",
    chapterName: "Phép nhân chia số lớn",
    title: "Kiểm tra Phép nhân chia số lớn",
    description: "Bài kiểm tra kỹ năng nhân chia các số lớn",
    duration: 35,
    questions: [
      { questionText: "234 × 5 = ?", questionType: "multiple_choice", options: ["A. 1070", "B. 1170", "C. 1270", "D. 1175"], correctAnswer: "B", points: 1 },
      { questionText: "4567 × 3 = ?", questionType: "fill_blank", options: [], correctAnswer: "13701", points: 1 },
      { questionText: "896 ÷ 4 = ?", questionType: "fill_blank", options: [], correctAnswer: "224", points: 1 },
      { questionText: "1234 × 6 = ?", questionType: "multiple_choice", options: ["A. 7404", "B. 7304", "C. 7204", "D. 7504"], correctAnswer: "A", points: 1 },
      { questionText: "5678 ÷ 2 = ?", questionType: "fill_blank", options: [], correctAnswer: "2839", points: 1 },
      { questionText: "Một xưởng mỗi ngày sản xuất 345 sản phẩm. Hỏi trong 7 ngày xưởng sản xuất được bao nhiêu sản phẩm?", questionType: "fill_blank", options: [], correctAnswer: "2415", points: 1 },
      { questionText: "3456 ÷ 8 = ?", questionType: "multiple_choice", options: ["A. 432", "B. 422", "C. 442", "D. 412"], correctAnswer: "A", points: 1 },
      { questionText: "Tìm x: x × 4 = 3648", questionType: "fill_blank", options: [], correctAnswer: "912", points: 1 },
      { questionText: "567 × 9 = ?", questionType: "fill_blank", options: [], correctAnswer: "5103", points: 1 },
      { questionText: "Có 4560 quyển sách chia đều cho 8 lớp. Mỗi lớp nhận được bao nhiêu quyển?", questionType: "fill_blank", options: [], correctAnswer: "570", points: 1 },
    ]
  },
  {
    grade: 4,
    subject: "toan",
    chapter: "chuong-3",
    chapterName: "Phân số",
    title: "Kiểm tra Phân số",
    description: "Bài kiểm tra kiến thức về phân số",
    duration: 30,
    questions: [
      { questionText: "Phân số 3/4 có tử số là bao nhiêu?", questionType: "multiple_choice", options: ["A. 3", "B. 4", "C. 7", "D. 1"], correctAnswer: "A", points: 1 },
      { questionText: "Phân số 5/5 bằng bao nhiêu?", questionType: "fill_blank", options: [], correctAnswer: "1", points: 1 },
      { questionText: "So sánh: 2/3 ... 3/4", questionType: "multiple_choice", options: ["A. >", "B. <", "C. =", "D. Không so sánh được"], correctAnswer: "B", points: 1 },
      { questionText: "Rút gọn phân số 6/8:", questionType: "fill_blank", options: [], correctAnswer: "3/4", points: 1 },
      { questionText: "1/2 + 1/4 = ?", questionType: "multiple_choice", options: ["A. 2/6", "B. 3/4", "C. 1/3", "D. 2/4"], correctAnswer: "B", points: 1 },
      { questionText: "3/5 - 1/5 = ?", questionType: "fill_blank", options: [], correctAnswer: "2/5", points: 1 },
      { questionText: "Phân số nào lớn hơn: 2/5 hay 3/5?", questionType: "fill_blank", options: [], correctAnswer: "3/5", points: 1 },
      { questionText: "Quy đồng mẫu số: 1/3 và 1/4. Mẫu số chung là:", questionType: "multiple_choice", options: ["A. 7", "B. 12", "C. 3", "D. 4"], correctAnswer: "B", points: 1 },
      { questionText: "2/3 của 12 bằng bao nhiêu?", questionType: "fill_blank", options: [], correctAnswer: "8", points: 1 },
      { questionText: "Viết phân số chỉ phần bị tô màu của hình vuông chia thành 4 phần bằng nhau, tô màu 3 phần:", questionType: "fill_blank", options: [], correctAnswer: "3/4", points: 1 },
    ]
  },
  {
    grade: 4,
    subject: "toan",
    chapter: "chuong-4",
    chapterName: "Hai đường thẳng vuông góc, song song. Hình thang",
    title: "Kiểm tra Hình học - Đường thẳng và hình thang",
    description: "Bài kiểm tra kiến thức về đường vuông góc, song song và hình thang",
    duration: 30,
    questions: [
      { questionText: "Hai đường thẳng vuông góc tạo với nhau góc bao nhiêu độ?", questionType: "multiple_choice", options: ["A. 45°", "B. 60°", "C. 90°", "D. 180°"], correctAnswer: "C", points: 1 },
      { questionText: "Hai đường thẳng song song thì khoảng cách giữa chúng:", questionType: "multiple_choice", options: ["A. Tăng dần", "B. Giảm dần", "C. Luôn bằng nhau", "D. Thay đổi"], correctAnswer: "C", points: 1 },
      { questionText: "Hình thang có mấy cặp cạnh đối song song?", questionType: "fill_blank", options: [], correctAnswer: "1", points: 1 },
      { questionText: "Hình thang vuông có mấy góc vuông?", questionType: "multiple_choice", options: ["A. 1", "B. 2", "C. 3", "D. 4"], correctAnswer: "B", points: 1 },
      { questionText: "Để vẽ hai đường thẳng vuông góc, em dùng:", questionType: "fill_blank", options: [], correctAnswer: "ê-ke", points: 1 },
      { questionText: "Hình thang cân có đặc điểm gì?", questionType: "multiple_choice", options: ["A. Hai đáy bằng nhau", "B. Hai cạnh bên bằng nhau", "C. Bốn góc vuông", "D. Bốn cạnh bằng nhau"], correctAnswer: "B", points: 1 },
      { questionText: "Diện tích hình thang = ?", questionType: "multiple_choice", options: ["A. (Đáy lớn + Đáy nhỏ) × Chiều cao", "B. (Đáy lớn + Đáy nhỏ) × Chiều cao ÷ 2", "C. Đáy × Chiều cao", "D. Đáy lớn × Đáy nhỏ"], correctAnswer: "B", points: 1 },
      { questionText: "Một hình thang có đáy lớn 10 cm, đáy nhỏ 6 cm, chiều cao 4 cm. Diện tích là:", questionType: "fill_blank", options: [], correctAnswer: "32 cm2", points: 1 },
    ]
  },
  {
    grade: 4,
    subject: "toan",
    chapter: "chuong-5",
    chapterName: "Đại lượng và đo đại lượng",
    title: "Kiểm tra Đại lượng và đo đại lượng",
    description: "Bài kiểm tra kiến thức về các đại lượng: diện tích, thể tích, thời gian",
    duration: 30,
    questions: [
      { questionText: "1 ha = ? m2", questionType: "multiple_choice", options: ["A. 100 m2", "B. 1000 m2", "C. 10000 m2", "D. 100000 m2"], correctAnswer: "C", points: 1 },
      { questionText: "1 thế kỉ = ? năm", questionType: "fill_blank", options: [], correctAnswer: "100", points: 1 },
      { questionText: "1 tấn = ? kg", questionType: "fill_blank", options: [], correctAnswer: "1000", points: 1 },
      { questionText: "1 ngày = ? giờ", questionType: "fill_blank", options: [], correctAnswer: "24", points: 1 },
      { questionText: "1 năm = ? tháng", questionType: "multiple_choice", options: ["A. 6", "B. 10", "C. 12", "D. 24"], correctAnswer: "C", points: 1 },
      { questionText: "Đổi 5 tấn 200 kg = ? kg", questionType: "fill_blank", options: [], correctAnswer: "5200", points: 1 },
      { questionText: "Năm nhuận có bao nhiêu ngày?", questionType: "multiple_choice", options: ["A. 364", "B. 365", "C. 366", "D. 367"], correctAnswer: "C", points: 1 },
      { questionText: "Một kho thóc chứa 4 tấn 500 kg gạo. Số gạo bằng bao nhiêu kg?", questionType: "fill_blank", options: [], correctAnswer: "4500", points: 1 },
    ]
  },

  // ===== LỚP 4 - NGỮ VĂN =====
  {
    grade: 4,
    subject: "ngu-van",
    chapter: "chuong-1",
    chapterName: "Đọc hiểu văn bản kể chuyện",
    title: "Kiểm tra Đọc hiểu văn bản kể chuyện",
    description: "Bài kiểm tra kỹ năng đọc hiểu văn bản kể chuyện, nhận biết nhân vật và cốt truyện",
    duration: 30,
    questions: [
      { questionText: "Nhân vật chính trong truyện là:", questionType: "multiple_choice", options: ["A. Người kể chuyện", "B. Người quan trọng nhất trong truyện", "C. Tác giả", "D. Người đọc"], correctAnswer: "B", points: 1 },
      { questionText: "Yếu tố nào không thuộc cấu trúc câu chuyện?", questionType: "multiple_choice", options: ["A. Mở bài", "B. Thân bài", "C. Kết bài", "D. Lời tựa"], correctAnswer: "D", points: 1 },
      { questionText: "Cốt truyện là:", questionType: "multiple_choice", options: ["A. Tên truyện", "B. Chuỗi sự kiện chính tạo nên câu chuyện", "C. Tên tác giả", "D. Nơi xảy ra truyện"], correctAnswer: "B", points: 1 },
      { questionText: "Ngôi kể thứ nhất dùng đại từ xưng hô nào?", questionType: "fill_blank", options: [], correctAnswer: "tôi", points: 1 },
      { questionText: "Tác giả của truyện kể thường kể ở ngôi thứ mấy?", questionType: "multiple_choice", options: ["A. Chỉ ngôi thứ nhất", "B. Chỉ ngôi thứ ba", "C. Ngôi thứ nhất hoặc ngôi thứ ba", "D. Không có ngôi kể"], correctAnswer: "C", points: 1 },
      { questionText: "Nội dung chính của đoạn văn là:", questionType: "multiple_choice", options: ["A. Ý quan trọng nhất được nói đến", "B. Chi tiết phụ", "C. Tên truyện", "D. Tên tác giả"], correctAnswer: "A", points: 1 },
      { questionText: "Từ 'dũng cảm' có nghĩa là:", questionType: "fill_blank", options: [], correctAnswer: "có lòng can đảm không sợ hãi", points: 1 },
      { questionText: "Từ 'hăng hái' trái nghĩa với:", questionType: "fill_blank", options: [], correctAnswer: "lười biếng", points: 1 },
      { questionText: "Chi tiết nào cho thấy nhân vật buồn?", questionType: "multiple_choice", options: ["A. Nhân vật cười lớn", "B. Nhân vật khóc", "C. Nhân vật chạy nhảy", "D. Nhân vật hát"], correctAnswer: "B", points: 1 },
      { questionText: "Bài học rút ra từ câu chuyện gọi là:", questionType: "fill_blank", options: [], correctAnswer: "ý nghĩa", points: 1 },
    ]
  },
  {
    grade: 4,
    subject: "ngu-van",
    chapter: "chuong-2",
    chapterName: "Luyện từ và câu - Câu ghép, quan hệ từ",
    title: "Kiểm tra Luyện từ và câu - Câu ghép, quan hệ từ",
    description: "Bài kiểm tra kiến thức về câu ghép, quan hệ từ và đại từ",
    duration: 25,
    questions: [
      { questionText: "Câu nào là câu ghép?", questionType: "multiple_choice", options: ["A. Em đi học.", "B. Mẹ nấu cơm và em đi học.", "C. Hôm nay trời đẹp!", "D. Bạn tên là gì?"], correctAnswer: "B", points: 1 },
      { questionText: "Trong câu 'Trời mưa nên em ở nhà', từ 'nên' là:", questionType: "multiple_choice", options: ["A. Danh từ", "B. Động từ", "C. Quan hệ từ", "D. Tính từ"], correctAnswer: "C", points: 1 },
      { questionText: "Quan hệ từ 'vì...nên' chỉ mối quan hệ:", questionType: "multiple_choice", options: ["A. Nguyên nhân - kết quả", "B. Tương phản", "C. Tiếp nối", "D. Điều kiện"], correctAnswer: "A", points: 1 },
      { questionText: "Thêm quan hệ từ vào: 'Em học chăm ... được điểm cao'", questionType: "fill_blank", options: [], correctAnswer: "nên", points: 1 },
      { questionText: "Từ 'nhưng' chỉ mối quan hệ:", questionType: "multiple_choice", options: ["A. Nguyên nhân", "B. Tương phản", "C. Tiếp nối", "D. Điều kiện"], correctAnswer: "B", points: 1 },
      { questionText: "Tách câu ghép thành 2 câu đơn: 'Nam học giỏi còn Lan học khá'", questionType: "fill_blank", options: [], correctAnswer: "Nam học giỏi. Lan học khá.", points: 1 },
      { questionText: "Đại từ dùng để thay thế danh từ nhằm:", questionType: "multiple_choice", options: ["A. Làm câu dài hơn", "B. Tránh lặp từ", "C. Thêm chi tiết", "D. Đổi chủ ngữ"], correctAnswer: "B", points: 1 },
      { questionText: "Điền quan hệ từ: 'Trời nắng ... em vẫn mang ô'", questionType: "fill_blank", options: [], correctAnswer: "nhưng", points: 1 },
      { questionText: "Quan hệ từ 'nếu...thì' chỉ mối quan hệ:", questionType: "multiple_choice", options: ["A. Nguyên nhân - kết quả", "B. Tương phản", "C. Điều kiện", "D. Tiếp nối"], correctAnswer: "C", points: 1 },
      { questionText: "Câu 'Tuy trời mưa nhưng chúng em vẫn đi học.' có mấy vế câu?", questionType: "fill_blank", options: [], correctAnswer: "2", points: 1 },
    ]
  },
  {
    grade: 4,
    subject: "ngu-van",
    chapter: "chuong-3",
    chapterName: "Tập làm văn - Viết văn miêu tả",
    title: "Kiểm tra Tập làm văn - Viết văn miêu tả",
    description: "Bài kiểm tra kỹ năng viết văn miêu tả sự vật, con vật, cảnh vật",
    duration: 30,
    questions: [
      { questionText: "Văn miêu tả là loại văn dùng để:", questionType: "multiple_choice", options: ["A. Kể lại một câu chuyện", "B. Giới thiệu đặc điểm sự vật, hiện tượng", "C. Nêu ý kiến đánh giá", "D. Hướng dẫn làm việc"], correctAnswer: "B", points: 1 },
      { questionText: "Khi miêu tả cây bàng, ta cần quan sát:", questionType: "multiple_choice", options: ["A. Chỉ màu sắc", "B. Chỉ hình dáng", "C. Hình dáng, màu sắc, âm thanh...", "D. Chỉ kích thước"], correctAnswer: "C", points: 1 },
      { questionText: "Dàn ý bài văn miêu tả gồm mấy phần?", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "Phần mở bài trong văn miêu tả cần:", questionType: "multiple_choice", options: ["A. Tả chi tiết sự vật", "B. Giới thiệu sự vật được tả", "C. Nêu cảm nghĩ", "D. Kể lại sự việc"], correctAnswer: "B", points: 1 },
      { questionText: "Phần kết bài trong văn miêu tả thường nêu:", questionType: "fill_blank", options: [], correctAnswer: "cảm nghĩ", points: 1 },
      { questionText: "Biện pháp nhân hóa là:", questionType: "multiple_choice", options: ["A. So sánh hai sự vật", "B. Gọi sự vật bằng từ ngữ dùng cho con người", "C. Nói quá sự thật", "D. Nói ngược ý"], correctAnswer: "B", points: 1 },
      { questionText: "Câu nào có biện pháp so sánh?", questionType: "multiple_choice", options: ["A. Bông hoa hồng đỏ rực.", "B. Mặt trời như một quả cầu lửa.", "C. Trời hôm nay rất nắng.", "D. Mùa thu có gió mát."], correctAnswer: "B", points: 1 },
      { questionText: "Từ gợi tả màu sắc trong câu 'Bầu trời xanh biếc' là:", questionType: "fill_blank", options: [], correctAnswer: "xanh biếc", points: 1 },
      { questionText: "Khi tả con vật, em nên tả theo thứ tự:", questionType: "multiple_choice", options: ["A. Tả thói quen trước, hình dáng sau", "B. Tả bao quát rồi tả chi tiết từng phần", "C. Tả tiếng kêu trước, hình dáng sau", "D. Không cần thứ tự"], correctAnswer: "B", points: 1 },
      { questionText: "Biện pháp nói quá (phóng đại) có trong câu:", questionType: "multiple_choice", options: ["A. Cây cao đến tận mây.", "B. Cây cao ba mét.", "C. Cây có tán rộng.", "D. Cây xanh tốt."], correctAnswer: "A", points: 1 },
    ]
  },

  // ===== LỚP 5 - TOÁN =====
  {
    grade: 5,
    subject: "toan",
    chapter: "chuong-1",
    chapterName: "Phân số thập phân và số thập phân",
    title: "Kiểm tra Phân số thập phân và số thập phân",
    description: "Bài kiểm tra kiến thức về phân số thập phân và số thập phân",
    duration: 30,
    questions: [
      { questionText: "Viết 3/10 dưới dạng số thập phân:", questionType: "multiple_choice", options: ["A. 0,03", "B. 0,3", "C. 3,0", "D. 0,13"], correctAnswer: "B", points: 1 },
      { questionText: "Viết 25/100 dưới dạng số thập phân:", questionType: "fill_blank", options: [], correctAnswer: "0,25", points: 1 },
      { questionText: "Số 4,56 đọc là:", questionType: "multiple_choice", options: ["A. Bốn phẩy năm mươi sáu", "B. Bốn phẩy năm trăm sáu mươi", "C. Bốn phẩy năm mươi sáu", "D. Bốn mươi phẩy năm sáu"], correctAnswer: "A", points: 1 },
      { questionText: "So sánh: 3,45 ... 3,54", questionType: "fill_blank", options: [], correctAnswer: "<", points: 1 },
      { questionText: "Chữ số 5 trong số 12,56 thuộc hàng nào?", questionType: "multiple_choice", options: ["A. Hàng đơn vị", "B. Hàng phần mười", "C. Hàng phần trăm", "D. Hàng chục"], correctAnswer: "B", points: 1 },
      { questionText: "Viết số thập phân: Không phẩy ba mươi bảy =", questionType: "fill_blank", options: [], correctAnswer: "0,37", points: 1 },
      { questionText: "Làm tròn số 3,46 đến hàng phần mười:", questionType: "multiple_choice", options: ["A. 3,4", "B. 3,5", "C. 3,6", "D. 3,0"], correctAnswer: "B", points: 1 },
      { questionText: "Chuyển 45% thành số thập phân:", questionType: "fill_blank", options: [], correctAnswer: "0,45", points: 1 },
      { questionText: "3,5 = ?/10. Tìm số thích hợp:", questionType: "fill_blank", options: [], correctAnswer: "35", points: 1 },
      { questionText: "Sắp xếp từ nhỏ đến lớn: 2,5; 2,15; 2,51; 2,05", questionType: "fill_blank", options: [], correctAnswer: "2,05 2,15 2,5 2,51", points: 1 },
    ]
  },
  {
    grade: 5,
    subject: "toan",
    chapter: "chuong-2",
    chapterName: "Phép tính với số thập phân",
    title: "Kiểm tra Phép tính với số thập phân",
    description: "Bài kiểm tra kỹ năng tính cộng trừ nhân chia số thập phân",
    duration: 35,
    questions: [
      { questionText: "3,5 + 2,7 = ?", questionType: "multiple_choice", options: ["A. 5,2", "B. 6,2", "C. 5,12", "D. 6,12"], correctAnswer: "B", points: 1 },
      { questionText: "8,4 - 3,6 = ?", questionType: "fill_blank", options: [], correctAnswer: "4,8", points: 1 },
      { questionText: "2,5 × 4 = ?", questionType: "multiple_choice", options: ["A. 8,5", "B. 9,0", "C. 10,0", "D. 100"], correctAnswer: "C", points: 1 },
      { questionText: "7,2 ÷ 3 = ?", questionType: "fill_blank", options: [], correctAnswer: "2,4", points: 1 },
      { questionText: "Tìm x: x + 3,45 = 7,8", questionType: "fill_blank", options: [], correctAnswer: "4,35", points: 1 },
      { questionText: "0,5 × 0,4 = ?", questionType: "multiple_choice", options: ["A. 0,2", "B. 0,9", "C. 2,0", "D. 0,09"], correctAnswer: "A", points: 1 },
      { questionText: "12,6 ÷ 6 = ?", questionType: "fill_blank", options: [], correctAnswer: "2,1", points: 1 },
      { questionText: "Một thanh kim loại dài 3,5m, cắt đi 1,25m. Còn lại bao nhiêu mét?", questionType: "fill_blank", options: [], correctAnswer: "2,25", points: 1 },
      { questionText: "4,8 + 2,35 = ?", questionType: "multiple_choice", options: ["A. 6,15", "B. 7,15", "C. 6,43", "D. 7,05"], correctAnswer: "B", points: 1 },
      { questionText: "1,5 × 6 = ?", questionType: "fill_blank", options: [], correctAnswer: "9", points: 1 },
    ]
  },
  {
    grade: 5,
    subject: "toan",
    chapter: "chuong-3",
    chapterName: "Diện tích và thể tích",
    title: "Kiểm tra Diện tích và thể tích",
    description: "Bài kiểm tra kiến thức về đại lượng và phép đo lường",
    duration: 30,
    questions: [
      { questionText: "1 km bằng bao nhiêu m?", questionType: "multiple_choice", options: ["A. 10 m", "B. 100 m", "C. 1000 m", "D. 10000 m"], correctAnswer: "C", points: 1 },
      { questionText: "1 tấn bằng bao nhiêu kg?", questionType: "fill_blank", options: [], correctAnswer: "1000", points: 1 },
      { questionText: "1 ha bằng bao nhiêu m²?", questionType: "multiple_choice", options: ["A. 100 m²", "B. 1000 m²", "C. 10000 m²", "D. 100000 m²"], correctAnswer: "C", points: 1 },
      { questionText: "2,5 km = ... m. Số cần điền là:", questionType: "fill_blank", options: [], correctAnswer: "2500", points: 1 },
      { questionText: "3 giờ 20 phút bằng bao nhiêu phút?", questionType: "multiple_choice", options: ["A. 180 phút", "B. 200 phút", "C. 320 phút", "D. 150 phút"], correctAnswer: "B", points: 1 },
      { questionText: "0,5 tấn = ... kg. Số cần điền là:", questionType: "fill_blank", options: [], correctAnswer: "500", points: 1 },
      { questionText: "Diện tích hình chữ nhật có chiều dài 5m, chiều rộng 3m là:", questionType: "fill_blank", options: [], correctAnswer: "15", points: 1 },
      { questionText: "1 thế kỉ bằng bao nhiêu năm?", questionType: "multiple_choice", options: ["A. 10 năm", "B. 100 năm", "C. 1000 năm", "D. 50 năm"], correctAnswer: "B", points: 1 },
      { questionText: "Chu vi hình chữ nhật có chiều dài 8m, chiều rộng 5m là:", questionType: "fill_blank", options: [], correctAnswer: "26", points: 1 },
      { questionText: "4500 g = ... kg. Số cần điền là:", questionType: "fill_blank", options: [], correctAnswer: "4,5", points: 1 },
    ]
  },
  {
    grade: 5,
    subject: "toan",
    chapter: "chuong-4",
    chapterName: "Tỉ số. Tỉ số phần trăm",
    title: "Kiểm tra Tỉ số và tỉ số phần trăm",
    description: "Bài kiểm tra kiến thức về tỉ số và tỉ số phần trăm",
    duration: 30,
    questions: [
      { questionText: "Tỉ số của 6 và 3 là:", questionType: "multiple_choice", options: ["A. 2", "B. 3", "C. 0,5", "D. 9"], correctAnswer: "A", points: 1 },
      { questionText: "25% = ? (dạng phân số)", questionType: "fill_blank", options: [], correctAnswer: "1/4", points: 1 },
      { questionText: "50% của 80 là:", questionType: "fill_blank", options: [], correctAnswer: "40", points: 1 },
      { questionText: "10% = ? (dạng số thập phân)", questionType: "multiple_choice", options: ["A. 0,1", "B. 0,01", "C. 1,0", "D. 0,5"], correctAnswer: "A", points: 1 },
      { questionText: "Một lớp có 40 học sinh, trong đó 25% là học sinh giỏi. Hỏi có bao nhiêu học sinh giỏi?", questionType: "fill_blank", options: [], correctAnswer: "10", points: 1 },
      { questionText: "75% = ? (dạng phân số)", questionType: "multiple_choice", options: ["A. 1/4", "B. 1/2", "C. 3/4", "D. 2/3"], correctAnswer: "C", points: 1 },
      { questionText: "100% của 45 là:", questionType: "fill_blank", options: [], correctAnswer: "45", points: 1 },
      { questionText: "Giá một quyển sách là 20000 đồng, giảm 10%. Số tiền giảm là:", questionType: "fill_blank", options: [], correctAnswer: "2000", points: 1 },
      { questionText: "Tỉ số phần trăm của 1/5 là:", questionType: "multiple_choice", options: ["A. 10%", "B. 20%", "C. 25%", "D. 50%"], correctAnswer: "B", points: 1 },
      { questionText: "Trong một tổ có 8 bạn nam và 12 bạn nữ. Tỉ số phần trăm bạn nam là:", questionType: "multiple_choice", options: ["A. 30%", "B. 40%", "C. 50%", "D. 60%"], correctAnswer: "B", points: 1 },
    ]
  },
  {
    grade: 5,
    subject: "toan",
    chapter: "chuong-5",
    chapterName: "Hình tròn và biểu đồ",
    title: "Kiểm tra Hình tròn và biểu đồ",
    description: "Bài kiểm tra kiến thức về hình tròn, chu vi, diện tích hình tròn và đọc biểu đồ",
    duration: 30,
    questions: [
      { questionText: "Diện tích hình tròn bán kính r được tính bằng công thức:", questionType: "multiple_choice", options: ["A. 2 × r × π", "B. r × r × π", "C. r × π", "D. 2 × r × r × π"], correctAnswer: "B", points: 1 },
      { questionText: "Thể tích hình hộp chữ nhật = ?", questionType: "multiple_choice", options: ["A. Dài × Rộng × Cao", "B. Dài + Rộng + Cao", "C. (Dài + Rộng) × Cao", "D. Dài × Rộng + Cao"], correctAnswer: "A", points: 1 },
      { questionText: "Chu vi hình tròn bán kính 7 cm là (lấy π ≈ 22/7):", questionType: "fill_blank", options: [], correctAnswer: "44 cm", points: 1 },
      { questionText: "Thể tích hình hộp chữ nhật dài 5 cm, rộng 3 cm, cao 4 cm là:", questionType: "fill_blank", options: [], correctAnswer: "60 cm3", points: 1 },
      { questionText: "Đơn vị đo thể tích là:", questionType: "multiple_choice", options: ["A. cm2", "B. cm3", "C. cm", "D. kg"], correctAnswer: "B", points: 1 },
      { questionText: "1 m3 = ? dm3", questionType: "fill_blank", options: [], correctAnswer: "1000", points: 1 },
      { questionText: "Diện tích hình tròn bán kính 5 cm là (lấy π ≈ 3,14):", questionType: "multiple_choice", options: ["A. 31,4 cm2", "B. 78,5 cm2", "C. 15,7 cm2", "D. 50 cm2"], correctAnswer: "B", points: 1 },
      { questionText: "Một bể nước hình hộp chữ nhật dài 2 m, rộng 1,5 m, cao 1 m. Thể tích bể là:", questionType: "fill_blank", options: [], correctAnswer: "3 m3", points: 1 },
    ]
  },

  // ===== LỚP 5 - NGỮ VĂN =====
  {
    grade: 5,
    subject: "ngu-van",
    chapter: "chuong-1",
    chapterName: "Đọc hiểu văn bản nghị luận và miêu tả",
    title: "Kiểm tra Đọc hiểu văn bản nghị luận và miêu tả",
    description: "Bài kiểm tra kỹ năng đọc hiểu văn bản nghị luận và miêu tả, tìm luận điểm và ý chính",
    duration: 30,
    questions: [
      { questionText: "Văn bản nghị luận là văn bản dùng để:", questionType: "multiple_choice", options: ["A. Kể lại câu chuyện", "B. Nêu ý kiến, quan điểm và lý lẽ", "C. Miêu tả sự vật", "D. Hướng dẫn làm việc"], correctAnswer: "B", points: 1 },
      { questionText: "Luận điểm là:", questionType: "multiple_choice", options: ["A. Chi tiết phụ", "B. Ý kiến chính được nêu trong văn bản nghị luận", "C. Câu hỏi của tác giả", "D. Lời tựa"], correctAnswer: "B", points: 1 },
      { questionText: "Văn miêu tả khác văn kể chuyện ở điểm:", questionType: "multiple_choice", options: ["A. Văn miêu tả giới thiệu đặc điểm sự vật", "B. Văn miêu tả kể lại sự việc", "C. Văn miêu tả nêu lý lẽ", "D. Giống nhau"], correctAnswer: "A", points: 1 },
      { questionText: "Câu nào là câu miêu tả?", questionType: "multiple_choice", options: ["A. Em đi học mỗi ngày.", "B. Bông hoa hồng đỏ rực như một ngọn lửa.", "C. Mẹ nấu cơm.", "D. Hôm nay là thứ mấy?"], correctAnswer: "B", points: 1 },
      { questionText: "Biện pháp tu từ so sánh sử dụng từ ngữ nào?", questionType: "fill_blank", options: [], correctAnswer: "như", points: 1 },
      { questionText: "Biện pháp nhân hóa là:", questionType: "multiple_choice", options: ["A. So sánh hai sự vật", "B. Gọi sự vật bằng từ ngữ dùng cho con người", "C. Nói quá sự thật", "D. Nói ngược ý"], correctAnswer: "B", points: 1 },
      { questionText: "Trong văn bản nghị luận, lý lẽ dùng để:", questionType: "fill_blank", options: [], correctAnswer: "chứng minh luận điểm", points: 1 },
      { questionText: "Dàn ý bài văn miêu tả gồm mấy phần?", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "Từ gợi tả màu sắc trong câu 'Bầu trời xanh biếc' là:", questionType: "fill_blank", options: [], correctAnswer: "xanh biếc", points: 1 },
      { questionText: "Biện pháp nói quá (phóng đại) có trong câu:", questionType: "multiple_choice", options: ["A. Cây cao đến tận mây.", "B. Cây cao ba mét.", "C. Cây có tán rộng.", "D. Cây xanh tốt."], correctAnswer: "A", points: 1 },
    ]
  },
  {
    grade: 5,
    subject: "ngu-van",
    chapter: "chuong-2",
    chapterName: "Luyện từ và câu - Từ nhiều nghĩa, câu mở rộng thành phần",
    title: "Kiểm tra Luyện từ và câu - Từ nhiều nghĩa, câu mở rộng thành phần",
    description: "Bài kiểm tra kiến thức về từ nhiều nghĩa, từ đồng âm và mở rộng thành phần câu",
    duration: 25,
    questions: [
      { questionText: "Từ nhiều nghĩa là từ:", questionType: "multiple_choice", options: ["A. Chỉ có một nghĩa", "B. Có nhiều nghĩa, nghĩa phụ phái sinh từ nghĩa gốc", "C. Viết giống nhau nhưng nghĩa khác nhau", "D. Đọc khác nhau"], correctAnswer: "B", points: 1 },
      { questionText: "Từ đồng âm là từ:", questionType: "multiple_choice", options: ["A. Có nhiều nghĩa phái sinh", "B. Viết và đọc giống nhau nhưng nghĩa không liên quan", "C. Có nghĩa trái ngược", "D. Có nghĩa giống nhau"], correctAnswer: "B", points: 1 },
      { questionText: "Trong câu 'Con đường đi' và 'Con đường về', từ 'đường' là:", questionType: "multiple_choice", options: ["A. Từ nhiều nghĩa", "B. Từ đồng âm", "C. Từ trái nghĩa", "D. Từ đồng nghĩa"], correctAnswer: "A", points: 1 },
      { questionText: "Từ 'bàn' trong 'cái bàn' và 'bàn bạc' là:", questionType: "fill_blank", options: [], correctAnswer: "từ đồng âm", points: 1 },
      { questionText: "Nghĩa gốc của từ 'mắt' là:", questionType: "multiple_choice", options: ["A. Mắt chân", "B. Bộ phận nhìn trên mặt", "C. Mắt dứa", "D. Mắt bão"], correctAnswer: "B", points: 1 },
      { questionText: "Mở rộng câu bằng cách thêm trạng ngữ là thêm:", questionType: "multiple_choice", options: ["A. Chủ ngữ", "B. Vị ngữ", "C. Từ chỉ thời gian, nơi chốn", "D. Tính từ"], correctAnswer: "C", points: 1 },
      { questionText: "Từ 'chân' trong 'chân núi' mang nghĩa:", questionType: "fill_blank", options: [], correctAnswer: "phần dưới của núi", points: 1 },
      { questionText: "Mở rộng câu: 'Em đi học.' bằng cách thêm trạng ngữ chỉ nơi chốn:", questionType: "fill_blank", options: [], correctAnswer: "Ở trường em đi học.", points: 1 },
      { questionText: "Từ nào là từ đồng âm với 'đường' (con đường)?", questionType: "multiple_choice", options: ["A. Đường (đường đi)", "B. Đường (đường ăn)", "C. Đường (đường phố)", "D. Đường (đường sá)"], correctAnswer: "B", points: 1 },
      { questionText: "Thêm bổ ngữ cho câu 'Em đọc' để thành câu đầy đủ hơn:", questionType: "fill_blank", options: [], correctAnswer: "Em đọc sách.", points: 1 },
    ]
  },
  {
    grade: 5,
    subject: "ngu-van",
    chapter: "chuong-3",
    chapterName: "Tập làm văn - Viết văn nghị luận cơ bản",
    title: "Kiểm tra Tập làm văn - Viết văn nghị luận cơ bản",
    description: "Bài kiểm tra kỹ năng viết văn nghị luận đơn giản, nêu ý kiến và lý lẽ",
    duration: 30,
    questions: [
      { questionText: "Văn nghị luận cần có:", questionType: "multiple_choice", options: ["A. Chỉ nêu ý kiến", "B. Ý kiến và lý lẽ chứng minh", "C. Chỉ kể chuyện", "D. Chỉ miêu tả"], correctAnswer: "B", points: 1 },
      { questionText: "Dàn ý bài văn nghị luận gồm mấy phần?", questionType: "fill_blank", options: [], correctAnswer: "3", points: 1 },
      { questionText: "Phần mở bài trong văn nghị luận cần:", questionType: "multiple_choice", options: ["A. Nêu lý lẽ", "B. Giới thiệu vấn đề cần nghị luận", "C. Kể lại câu chuyện", "D. Miêu tả sự vật"], correctAnswer: "B", points: 1 },
      { questionText: "Phần thân bài trong văn nghị luận cần:", questionType: "fill_blank", options: [], correctAnswer: "nêu lý lẽ chứng minh", points: 1 },
      { questionText: "Phần kết bài trong văn nghị luận cần:", questionType: "multiple_choice", options: ["A. Nêu lại ý kiến chính", "B. Kể lại câu chuyện", "C. Miêu tả sự vật", "D. Hỏi câu hỏi"], correctAnswer: "A", points: 1 },
      { questionText: "Để chứng minh ý kiến 'Học sinh cần đi học đúng giờ', em có thể dùng lý lẽ nào?", questionType: "multiple_choice", options: ["A. Đi học muốn thì đi", "B. Đi học đúng giờ giúp tiếp thu bài tốt hơn", "C. Bạn bè đi học trễ cũng được", "D. Không cần lý lẽ"], correctAnswer: "B", points: 1 },
      { questionText: "Liên kết câu trong đoạn văn nghị luận giúp:", questionType: "multiple_choice", options: ["A. Làm câu dài hơn", "B. Các câu liên kết chặt chẽ, dễ hiểu", "C. Thêm chi tiết phụ", "D. Đổi chủ ngữ"], correctAnswer: "B", points: 1 },
      { questionText: "Từ nối thường dùng trong đoạn văn nghị luận là:", questionType: "fill_blank", options: [], correctAnswer: "tuy nhiên", points: 1 },
      { questionText: "Viết câu nêu ý kiến: 'Em nghĩ việc giữ gìn trường lớp sạch sẽ là...'", questionType: "fill_blank", options: [], correctAnswer: "rất quan trọng", points: 1 },
      { questionText: "Khi viết văn nghị luận, lý lẽ cần:", questionType: "multiple_choice", options: ["A. Chỉ nêu cảm xúc", "B. Hợp lý, thuyết phục", "C. Chỉ kể chuyện", "D. Chỉ miêu tả"], correctAnswer: "B", points: 1 },
    ]
  },
];

export default quizData;
